### ISSUE TITLE
Configure inventory for localhost

### ISSUE THREAD

**Issue by saint-hilaire** [saint-hilaire/ansible-directory-helper#1]
When creating the inventory file, if a host is some kind of localhost - either specifically `localhost` or also `127.0.0.1` - the proper configuration - the setting `ansible_connection: local` - needs to be added to that host. Otherwise, Ansible will try to connect via SSH, and likely fail.

In other words:

Where ansible-directory-helper currently generates this configuration:

```
group1:
  hosts:
    localhost:
      ansible_user: user1  
      inventory_dir: null
      inventory_file: null
```

It should generate this instead:

```
group1:
  hosts:
    localhost:
      ansible_user: user1  
      inventory_dir: null
      inventory_file: null
      ansible_connection: local
```

This is necessary for these issues in [Lampsible](https://github.com/saint-hilaire/lampsible) and [Docksible](https://github.com/saint-hilaire/docksible):

* https://github.com/saint-hilaire/lampsible/issues/25
* https://github.com/saint-hilaire/docksible/issues/15
